### ISSUE TITLE
Getting 401 Unauthorized

### ISSUE THREAD

**Issue by jml6m** [eksoverzero/newrelic_elasticsearch_agent#12]
ERROR while gathering stats from `http://username:password@our.domain.net:8080`: 401 Unauthorized

where username and password are correct credentials (the URL works when loaded in the browser). We've tried various variations of the connection string but it never connects.

Here is my YML file:

```
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'MYKEY'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1

#
# Agent Configuration, describe your nginx instances here
#
agents:
  elasticsearch_stats_agent:
    -
      # Application name
      name: "ES1P"
      # Index name
      # using "_all" with provide stats for all indices
      index: "_all"
      url: "http://username:password@our.domain.net:8080"
```
